<?php
$products = [
	[
		"id" => 1,
		"product_name" => "RUMKLEEN ANTIBACTERIAL HAND CREAM",
		"distinct" => "ORANGE",
		"quantity" => "300ML",
		"amount" => "120.00",
		"image" => "rumkleen_antibacterial_handcream_orange_300ml.jpg",
	],
	[
		"id" => 2,
		"product_name" => "RUMKLEEN ANTIBACTERIAL HAND CREAM",
		"distinct" => "ORANGE",
		"quantity" => "500ML",
		"amount" => "176.00",
		"image" => "rumkleen_antibacterial_handcream_orange_500ml.jpg",
	],
	[
		"id" => 3,
		"product_name" => "RUMKLEEN ANTIBACTERIAL HAND CREAM",
		"distinct" => "FRUIT PUNCH",
		"quantity" => "300ML",
		"amount" => "120.00",
		"image" => "rumkleen_antibacterial_handsoap_fruitpunch_300ml.jpg",
	],
	[
		"id" => 4,
		"product_name" => "RUMKLEEN ANTIBACTERIAL HAND CREAM",
		"distinct" => "FRUIT PUNCH",
		"quantity" => "500ML",
		"amount" => "176.00",
		"image" => "rumkleen_antibacterial_handsoap_fruitpunch_500ml.jpg",
	],
	[
		"id" => 5,
		"product_name" => "RUMKLEEN ANTIBACTERIAL HAND CREAM",
		"distinct" => "LEMON",
		"quantity" => "300ML",
		"amount" => "120.00",
		"image" => "rumkleen_antibacterial_handcream_lemon_300ml.jpg",
	],
	[
		"id" => 6,
		"product_name" => "RUMKLEEN ANTIBACTERIAL HAND CREAM",
		"distinct" => "LEMON",
		"quantity" => "500ML",
		"amount" => "176.00",
		"image" => "rumkleen_antibacterial_handcream_lemon_500ml.jpg",
	],
	[
		"id" => 7,
		"product_name" => "RUMKLEEN ANTIBACTERIAL HAND CREAM",
		"distinct" => "RASPERRY",
		"quantity" => "500ML",
		"amount" => "176.00",
		"image" => "rumkleen_antibacterial_handcream_rasperry_500ml.jpg",
	],
	[
		"id" => 8,
		"product_name" => "RUMKLEEN TOILET CLEANER AND DISINFECTANT 2 IN 1",
		"distinct" => "OCEAN BREEZE",
		"quantity" => "750ML",
		"amount" => "20.00",
		"image" => "rumkleen_toilet_cleaner_ocean_breeze_2in1_750ml.jpg",
	],
	[
		"id" => 9,
		"product_name" => "RUMKLEEN TOILET CLEANER AND DISINFECTANT 2 IN 1",
		"distinct" => "LAVENDER",
		"quantity" => "750ML",
		"amount" => "159.00",
		"image" => "rumkleen_toilet_cleaner_2in1_lavender_750ml.jpg",
	],
	[
		"id" => 10,
		"product_name" => "RUMKLEEN TOILET CLEANER AND DISINFECTANT 5 IN 1",
		"distinct" => "LAVENDER",
		"quantity" => "750ML",
		"amount" => "20.00",
		"image" => "rumkleen_toilet_cleaner_5in1_lavender_750ml.jpg",
	],
	[
		"id" => 11,
		"product_name" => "RUMKLEEN TOILET CLEANER AND DISINFECTANT 5 IN 1",
		"distinct" => "LAVENDER",
		"quantity" => "5LTRS",
		"amount" => "1,100.00",
		"image" => "rumkleen_toilet_cleaner_ocean_breeze_5in1_5ltrs.jpg",
	],
	[
		"id" => 12,
		"product_name" => "RUMKLEEN TOILET CLEANER AND DISINFECTANT 5 IN 1",
		"distinct" => "OCEAN BREEZE",
		"quantity" => "750ML",
		"amount" => "216.00",
		"image" => "rumkleen_toilet_cleaner_ocean_breeze_5in1_750ml.jpg",
	],
	[
		"id" => 13,
		"product_name" => "MORECARE HAND GEL SANITIZER",
		"distinct" => "NO WATER NO TOWEL",
		"quantity" => "50ML",
		"amount" => "85.00",
		"image" => "morecare_handgel_sanitizer_no_water_50ml.jpg",
	],
	[
		"id" => 14,
		"product_name" => "MORECARE HAND GEL SANITIZER",
		"distinct" => "NO WATER NO TOWEL",
		"quantity" => "100ML",
		"amount" => "110.00",
		"image" => "morecare_handgel_sanitizer_no_water_100ml.jpg",
	],
	[
		"id" => 15,
		"product_name" => "MORECARE HAND GEL SANITIZER",
		"distinct" => "NO WATER NO TOWEL",
		"quantity" => "250ML",
		"amount" => "185.00",
		"image" => "morecare_handgel_sanitizer_no_water_250ml.jpg",
	],
	[
		"id" => 16,
		"product_name" => "MORECARE HAND GEL SANITIZER",
		"distinct" => "NO WATER NO TOWEL",
		"quantity" => "5LTRS",
		"amount" => "2,500.00",
		"image" => "morecare_handgel_sanitizer_no_water_5ltrs.jpg",
	],
	[
		"id" => 17,
		"product_name" => "MORECARE HAND GEL SANITIZER",
		"distinct" => "NO WATER NO TOWEL",
		"quantity" => "500ML",
		"amount" => "340.00",
		"image" => "morecare_handgel_sanitizer_no_water_500ml.jpg",
	],
	[
		"id" => 18,
		"product_name" => "MORECARE HAND GEL SANITIZER",
		"distinct" => "PEACH",
		"quantity" => "50ML",
		"amount" => "85.00",
		"image" => "morecare_handgel_sanitizer_peach_50ml.jpg",
	],
	[
		"id" => 19,
		"product_name" => "MORECARE HAND GEL SANITIZER",
		"distinct" => "PEACH",
		"quantity" => "50ML",
		"amount" => "185.00",
		"image" => "morecare_handgel_sanitizer_peach_250ml.jpg",
	],
	[
		"id" => 20,
		"product_name" => "MORECARE HAND GEL SANITIZER",
		"distinct" => "ALOE VERA",
		"quantity" => "250ML",
		"amount" => "185.00",
		"image" => "morecare_handgel_sanitizer_aloevera_250ml.jpg",
	],
	[
		"id" => 21,
		"product_name" => "MORECARE HAND GEL SANITIZER",
		"distinct" => "ALOE VERA",
		"quantity" => "50ML",
		"amount" => "85.00",
		"image" => "morecare_handgel_sanitizer_aloevera_50ml.jpg",
	],
	[
		"id" => 22,
		"product_name" => "MORECARE ANTIBACTERIAL SHOWER GEL",
		"distinct" => "APRICOT",
		"quantity" => "300ML",
		"amount" => "240.00",
		"image" => "morecare_antibacterial_showergel_apricot_300ml.jpg",
	],
	[
		"id" => 23,
		"product_name" => "MORECARE ANTIBACTERIAL SHOWER GEL",
		"distinct" => "APRICOT",
		"quantity" => "600ML",
		"amount" => "440.00",
		"image" => "morecare_antibacterial_showergel_apricot_600ml.jpg",
	],
	[
		"id" => 24,
		"product_name" => "MORECARE ANTIBACTERIAL SHOWER GEL",
		"distinct" => "HERBAL",
		"quantity" => "300ML",
		"amount" => "240.00",
		"image" => "morecare_antibacterial_showergel_herbal_300ml.jpg",
	],
	[
		"id" => 25,
		"product_name" => "MORECARE ANTIBACTERIAL SHOWER GEL",
		"distinct" => "HERBAL",
		"quantity" => "600ML",
		"amount" => "440.00",
		"image" => "morecare_antibacterial_showergel_herbal_600ml.jpg",
	],
	[
		"id" => 26,
		"product_name" => "MORECARE ANTIBACTERIAL SHOWER GEL",
		"distinct" => "LAVENDER",
		"quantity" => "600ML",
		"amount" => "440.00",
		"image" => "morecare_antibacterial_showergel_lavender_600ml.jpg",
	],
	[
		"id" => 27,
		"product_name" => "MORECARE ANTIBACTERIAL SHOWER GEL",
		"distinct" => "LEMON",
		"quantity" => "300ML",
		"amount" => "240.00",
		"image" => "morecare_antibacterial_showergel_lemon_300ml.jpg",
	],
	[
		"id" => 28,
		"product_name" => "MORECARE ANTIBACTERIAL SHOWER GEL",
		"distinct" => "SHEA & VITAMINS",
		"quantity" => "300ML",
		"amount" => "240.00",
		"image" => "morecare_antibacterial_showergel_shea_and_vitamins_300ml.jpg",
	],
	[
		"id" => 29,
		"product_name" => "MORECARE ANTIBACTERIAL SHOWER GEL",
		"distinct" => "SHEA & VITAMINS",
		"quantity" => "600ML",
		"amount" => "440.00",
		"image" => "morecare_antibacterial_showergel_shea_and_vitamins_600ml.jpg",
	],
	[
		"id" => 30,
		"product_name" => "MORECARE ANTIBACTERIAL SHOWER GEL",
		"distinct" => "SOFT PEACH",
		"quantity" => "300ML",
		"amount" => "240.00",
		"image" => "morecare_antibacterial_showergel_softpeach_300ml.jpg",
	],
	[
		"id" => 31,
		"product_name" => "MORECARE ANTIBACTERIAL SHOWER GEL",
		"distinct" => "SOFT PEACH",
		"quantity" => "600ML",
		"amount" => "440.00",
		"image" => "morecare_antibacterial_showergel_softpeach_600ml.jpg",
	],
	[
		"id" => 32,
		"product_name" => "MORECARE ANTIBACTERIAL SHOWER GEL",
		"distinct" => "STRAWBERRY",
		"quantity" => "300ML",
		"amount" => "240.00",
		"image" => "morecare_antibacterial_showergel_strawberry_300ml.jpg",
	],
	[
		"id" => 33,
		"product_name" => "MORECARE ANTIBACTERIAL SHOWER GEL",
		"distinct" => "VANILLA",
		"quantity" => "300ML",
		"amount" => "240.00",
		"image" => "morecare_antibacterial_showergel_vanilla_300ml.jpg",
	],
	[
		"id" => 34,
		"product_name" => "MORECARE ANTIBACTERIAL SHOWER GEL",
		"distinct" => "VANILLA",
		"quantity" => "600ML",
		"amount" => "440.00",
		"image" => "morecare_antibacterial_showergel_vanilla_600ml.jpg",
	],
	[
		"id" => 35,
		"product_name" => "MORECARE HAND GEL SANITIZER",
		"distinct" => "NO WATER NO TOWEL",
		"quantity" => "20LTRS",
		"amount" => "9,000.00",
		"image" => "morecare_handgel_sanitizer_no_water_20ltrs.jpg",
	],	

];

?>